### ISSUE TITLE
imitator file not found!

### ISSUE THREAD

**Issue by aidenZou** [hanan198501/imitator#3]
Imitatorfile.js 文件真实存在

imitator
[WARN] imitator file not found!
Imitator server listening on port 8888

接口返回：

{"status":404,"message":"Not Found","err":{"status":404}}

**Comment by jason-ivy** [comment]
～～需要在/User/usename下新建Imitatorfile.js，而不是项目目录下，搞不明白作者为什么要这么做～～

**Comment by annnhan** [comment]
可以通过 imitator  -f 你的Imitatorfile.js路径 来指定配置文件，否则，默认取用户目录下的Imitatorfile.js 作为配置文件。

**Comment by jason-ivy** [comment]
建议改成默认为当前项目下的Imitatorfile.js 作为配置文件。
