### ISSUE TITLE
支持文件下载吗？

### ISSUE THREAD

**Issue by leopardpan** [hanan198501/imitator#5]
我使用了你的文件读取，但是读取出来的都是二进制流，能不能还原成原始的文件，或者下载Gzip文件之类的？

**Comment by annnhan** [comment]
可以在自定义返回内容result这么写：
imitator({
……
result: function (req, res) { // 下载/report-12345.pdf
res.download('/report-12345.pdf');
},
});

res参数是经过 express 包装的，可以使用任何 express 的 api，参考http://expressjs.com/api.html#res.download
